### ISSUE TITLE
Enable Cloudflare Worker Logs

### ISSUE THREAD

**Issue by therealstein** [unjs/nitro#2809]
### Describe the feature

To enable the new Cloudflare Worker logs, I need to modify the `wrangler.toml` file. I have already added a `wrangler.toml` in the root folder with the following configuration, but it didn't help:

```toml
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
```

Additionally, I can't find any `wrangler.toml` file in the `dist` folder.

Docs:  
https://developers.cloudflare.com/workers/observability/logs/workers-logs/

### Additional information

- [X] Would you be willing to help implement this feature?
